version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "15432:5432"
    volumes:
      - ~/Documents/Dev/node-gcalendar/docker-data/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "thbr28@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge